language: node_js

os: osx

node_js:
  - '8'
  - "9"

cache:
  directories:
    - node_modules

env:
  - ALLOW_HTTP=true

install:
  - npm install

before_script:
  - npm run build

script:
  npm run test
